[package]
name = "chemcat"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"

[dependencies]
chumsky = "0.7"
owo-colors = "3.2"
# ariadne = "0.1"

[profile.release]
overflow-checks = true
