[package]
name = "chemcat"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"

[dependencies]
ctrlc = "3"
chumsky = "0.9"
gcd = "2"
owo-colors = "3"
# ariadne = "0.1"

[profile.release]
overflow-checks = true
